name: Check GitHub Contributions And Notify

on:
  schedule:
    - cron: "30 13 * * *" # 毎日23時に実行
  workflow_dispatch: # GitHubの「Run workflow」ボタンから実行可能

jobs:
  check-and-notify:
    name: 本日のGitHubコントリビューションを確認してSlackに通知
    runs-on: ubuntu-latest
    environment: slack # GitHub > Settings > Environments を指定
    steps:
      - name: Check for Contributions
        # GitHub CLI が GitHub API にリクエストを送信するための認証トークンを指定
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GitHub CLI の gh コマンドを使い、GraphQL API にリクエスト
        # -F で変数を指定, -f query で実行したいGraphQLクエリを指定
        # jq でJSONから必要な情報を取得(標準出力の中から読み込むため事前に echo しておく)
        # TOTAL_CONTRIBUTIONS を $GITHUB_ENV にエクスポートして、後続のステップで利用
        run: |
          DATE=$(date -u +"%Y-%m-%dT00:00:00Z")
          USER=$GITHUB_REPOSITORY_OWNER

          RESPONSE=$(gh api graphql -F DATE=$DATE -F USER=$USER -f query='
            query ($DATE: DateTime, $USER: String!){
              user(login: $USER) {
                contributionsCollection(from: $DATE, to: $DATE) {
                  contributionCalendar{
                    totalContributions
                  }
                }
              }
            }
            '
          )
          echo "Response: $RESPONSE"
          TOTAL_CONTRIBUTIONS=$(echo $RESPONSE | jq '.data.user.contributionsCollection.contributionCalendar.totalContributions')
          echo "Total contributions: $TOTAL_CONTRIBUTIONS"

          echo "TOTAL_CONTRIBUTIONS=$TOTAL_CONTRIBUTIONS" >> $GITHUB_ENV

      # Slackに通知
      - name: Send Slack if No Contributions
        run: |
          echo "TOTAL_CONTRIBUTIONS: $TOTAL_CONTRIBUTIONS"
          if [ "$TOTAL_CONTRIBUTIONS" -gt 0 ]; then
            MESSAGE="本日のコントリビューション: $TOTAL_CONTRIBUTIONS 件"
          else
            MESSAGE="本日のコントリビューションがありません。"
          fi
          curl -X POST \
            -F channel=${{ secrets.SLACK_CHANNEL_ID }} \
            -F text="$MESSAGE" \
            https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer ${{ secrets.BOT_USER_OAUTH_TOKEN }}"
