name: Slack Notification Dispatch Test

on:
  workflow_dispatch: # GitHubの「Run workflow」ボタンから実行可能

jobs:
  notify:
    name: Slackへメッセージを送信
    runs-on: ubuntu-latest
    environment: slack # GitHub > Settings > Environments を指定
    steps:
      - name: Slackにメッセージ送信
        run: |
          curl -X POST \
          -F channel=${{ secrets.SLACK_CHANNEL_ID }} \
          -F text="テストだよ" https://slack.com/api/chat.postMessage \
          -H "Authorization: Bearer ${{ secrets.BOT_USER_OAUTH_TOKEN }}"
