name: Slack Notification

on:
  workflow_dispatch:

jobs:
  notify:
    name: Slackへ通知を送信
    runs-on: ubuntu-latest
    environment: slack
    steps:
      - name: Slackにメッセージ送信
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"text": "GitHub Actionsからの通知です！"}' \
            "${{ secrets.SLACK_WEBHOOK_URL }}"
